apiVersion: v2
name: centrifuge-api-v3
description: Helm chart for Centrifuge API v3 ponder based indexer
type: application
version: 0.1.20
appVersion: "1.16.0"
dependencies:
  - alias: postgres
    name: cluster
    condition: postgres.enabled
    version: 0.3.1
    repository: https://cloudnative-pg.github.io/charts
