{{- if .Values.indexer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centrifuge-api.indexer.fullname" . }}
  labels:
    {{- include "centrifuge-api.indexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.indexer.service.type }}
  ports:
    - port: {{ .Values.indexer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "centrifuge-api.indexer.selectorLabels" . | nindent 4 }}
{{- end }}
