{{- if .Values.indexer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "centrifuge-api.indexer.fullname" . }}
  labels:
    {{- include "centrifuge-api.indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.indexer.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "centrifuge-api.indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.indexer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "centrifuge-api.indexer.labels" . | nindent 8 }}
        {{- with .Values.indexer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.indexer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: indexer
          {{- with .Values.indexer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.indexer.service.port }}
              protocol: TCP
          {{- with .Values.indexer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.indexer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.indexer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.indexer.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.indexer.command }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName | default (printf "%s-postgres-app" .Release.Name) }}
                  key: uri
            - name: DATABASE_SCHEMA
              value: "{{ .Values.indexer.image.tag | default "latest" }}"
          {{- with .Values.indexer.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Values.global.apiSecretName }}
          {{- with .Values.indexer.envFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.indexer.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
