{{- if .Values.query.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "centrifuge-api.query.fullname" . }}
  labels:
    {{- include "centrifuge-api.query.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.query.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "centrifuge-api.query.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.query.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "centrifuge-api.query.labels" . | nindent 8 }}
        {{- with .Values.query.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.query.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.query.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: query
          {{- with .Values.query.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.query.image.repository }}:{{ .Values.query.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.query.image.pullPolicy }}
          args:
            {{- with .Values.query.command }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.dbSecretName | default (printf "%s-postgres-app" .Release.Name) }}
                  key: uri
            - name: DATABASE_SCHEMA
              value: "{{ .Values.query.image.tag | default "latest" }}"
          {{- with .Values.query.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Values.global.apiSecretName }}
          {{- with .Values.query.envFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.query.service.port }}
              protocol: TCP
          {{- with .Values.query.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.query.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.query.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.query.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.query.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.query.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.query.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.query.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
