{{- if .Values.query.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centrifuge-api.query.fullname" . }}
  labels:
    {{- include "centrifuge-api.query.labels" . | nindent 4 }}
spec:
  type: {{ .Values.query.service.type }}
  ports:
    - port: {{ .Values.query.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "centrifuge-api.query.selectorLabels" . | nindent 4 }}
{{- end }}
